server {
        listen  443 ssl;
        server_name wordbress.ahrensburg.wiki;

        root /wiki/wordbress;
        index index.php;
 ssl_certificate     /etc/letsencrypt/live/ahrensburg.wiki/fullchain.pem;
         ssl_certificate_key /etc/letsencrypt/live/ahrensburg.wiki/privkey.pem;

   location / {

                  try_files $uri $uri/ /index.php;
          }

          location ~ (^|/)\. {
                 return 403;
             }

             location ~ /vendor/.*\.php$ {
                 deny all;
                 return 404;
             }

          location ~ /\.ht {
            deny all;
           }

          location ~ \.php$ {
              fastcgi_pass unix:/run/php/php7.4-fpm.sock;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
              include snippets/fastcgi-php.conf;
          }
  }