server {
  listen       443 ssl;
    server_name  moodle.ahrensburg.city;
      ssl_certificate     /etc/letsencrypt/live/lernen.ahrensburg.city/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/lernen.ahrensburg.city/privkey.pem;
    root /wiki/moodle;
        index  index.php index.html index.htm;
        location / {
        root   /wiki/moodle;
        }


        location ~ [^/]\.php(/|$) {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }

    location /dataroot/ {
    internal;
    alias /wiki/wiki/moodledata;
    }
}