server {
listen  443 ssl;
        server_name ahrensburgwebverzeichnis.de;
 ssl_certificate     /etc/letsencrypt/live/ahrensburgwebverzeichnis.de/fullchain.pem;
         ssl_certificate_key /etc/letsencrypt/live/ahrensburgwebverzeichnis.de/privkey.pem;
    root /srv/nominatim/nominatim-project/start/website;
    index search.php index.html;
     location / {
            try_files \$uri \$uri/ @php;
        }

        location @php {
            fastcgi_param SCRIPT_FILENAME "\$document_root\$uri.php";
            fastcgi_param PATH_TRANSLATED "\$document_root\$uri.php";
            fastcgi_param QUERY_STRING    \$args;
            fastcgi_pass unix:/var/run/php7.4-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
        }



      location ~ [^/]\.php(/|$) {
          fastcgi_split_path_info ^(.+?\.php)(/.*)$;
          if (!-f \$document_root\$fastcgi_script_name) {
              return 404;
          }
          fastcgi_pass unix:/var/run/php7.4-fpm.sock;
          fastcgi_index search.php;
          include fastcgi.conf;
      }
  }