server {
        listen  443 ssl;
        server_name wordpress.ahrensburg.wiki;

        root /wiki/wordpress;
        index index.php;
 ssl_certificate     /etc/letsencrypt/live/wordpress.ahrensburg.wiki/fullchain.pem;
         ssl_certificate_key /etc/letsencrypt/live/wordpress.ahrensburg.wiki/privkey.pem;

   location / {

                  try_files $uri $uri/ /index.php;
          }



          location ~ /\.ht {
            deny all;
           }

          location ~ \.php$ {
              fastcgi_pass unix:/run/php/php7.4-fpm.sock;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
              include snippets/fastcgi-php.conf;
          }
  }